### ISSUE TITLE
Openapi spec endpoint or file

### ISSUE THREAD

**Issue by knippers** [wefabricate/wh-python#38]
This seemed to me the easiest place to ask for the openapi spec so I can use that to create a javascript client. Which then can be used to create a Homey app. Of course even better would be an official Weheat Homey app. Even though Athom is now LG owned I would still consider it Dutch innovation.

**Comment by erikgeurts** [comment]
I made my own API implementation in Home Assistant, and these are the end points I used:

```
- resource: 'https://auth.weheat.nl/auth/realms/Weheat/protocol/openid-connect/token'
  method: POST
  # The sensor below is being updated by an automation. However, scan_interval
  # can not be omitted, since it will then default to 30 seconds. Therefore,
  # use an interval of once per day to override the default.
  scan_interval: 86400
  headers:
    Content-Type: "application/x-www-form-urlencoded"
    Accept: "application/json"
    payload: !secret weheat_token_payload
(....)
```

I have a secrets.yaml file where I've defined the weheat_token_payload similar to this:
```
# this is the payload for the Weheat API access token request
weheat_token_payload: "grant_type=password&client_id=WeheatCommunityAPI&scope=openid&username=email@example.com&password=whatevermypasswordhappenstobe"

```

The username (email) and password are the same as those used to log in on the Weheat portal or app.

The endpoint above is used to request and update an API key for authentication in the other end points. I store the token in a template sensor in Home Assistant `sensor.weheat_api_token`, and then I used it as follows:

To request the current status of the heat pump:

```
- resource: https://api.weheat.nl/api/v1/heat-pumps/[heatpumpID]/logs/latest
  # The sensors below are being updated by an automation. However, scan_interval
  # can not be omitted, since it will then default to 30 seconds. Therefore,
  # use an interval of once per day to override the default.
  scan_interval: 86400
  headers:
    Accept: application/json
    Content-Type: application/json
    Authorization: >  
      {% set token = state_attr('sensor.weheat_api_token', 'access_token') %}  
      {{ 'Bearer ' ~ token if token else '' }}
(...)
```

At the time of this writing, there is a rate limiter that limits your use of the status API to 1 time per 120 seconds. Hopefully this will become less strict in the future.

And to request the energy logs for a date range:

```
- resource_template: "{{ states('https://api.weheat.nl/api/v1/energy-logs/[heatpumpID]') }}?startTime={{ states('input_text.weheat_energy_resource_start_time') }}&endTime={{ states('input_text.weheat_energy_resource_end_time') }}&interval={{ states('input_text.weheat_energy_resource_interval') }}"
  # The sensors below are being updated by an automation. However, scan_interval
  # can not be omitted, since it will then default to 30 seconds. Therefore,
  # use an interval of once per day to override the default.
  scan_interval: 86400
  headers:
    Accept: application/json
    Content-Type: application/json
    Authorization: >  
      {% set token = state_attr('sensor.weheat_api_token', 'access_token') %}  
      {{ 'Bearer ' ~ token if token else '' }}
(....)
```

The start time and end time would look something like this: `2025-04-30T22:00:00.000Z`. The interval can be something like Day, Month, Year.

Note: at the time of this writing, the energy logs end point will return a message that it is disabled temporarily due to technical issues. This has been the case since early February 2025. Hopefully it will be restored to active duty soon.

You can use something like Postman to retrieve these end points to see what the XML response looks like, so that you can process it for your own implementation.
